version: "3"
services:
  mysql:
    container_name: mysql8
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    security_opt:
        - seccomp:unconfined
    restart: always
    networks:
      - nacos-mysql 
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=nacos-config            #看情况
        - MYSQL_USER=nacos
        - MYSQL_PASSWORD=nacos
    volumes:
        - ./db:/docker-entrypoint-initdb.d/ #将nacos初始化sql放到db目录
        - ./data/mysql:/var/lib/mysql
        - ./conf/my.cnf:/etc/my.cnf
    ports:
      - "3306:3306"
  nacos:
    hostname: nacos
    container_name: nacos
    image: nacos/nacos-server:latest
    restart: always
    networks:
      - nacos-mysql 
    volumes:
      - ./data/cluster-logs/nacos:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9555:9555"
    environment:
      - PREFER_HOST_MODE=hostname
      - NACOS_SERVERS=standalone
      - MYSQL_SERVICE_HOST=mysql8
      - MYSQL_SERVICE_DB_NAME=nacos-config
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=nacos
      - MYSQL_SERVICE_PASSWORD=nacos

# 创建网络
networks:
  nacos-mysql:
    external: true