apiVersion: v1
kind: PersistentVolume
metadata:
  name: your-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  hostPath:
    path: /path/to/host/folder

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: your-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
